[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.25'
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true

[rpc_endpoints]
sepolia = "https://rpc.sepolia.org/"
op_sepolia = "https://sepolia.optimism.io"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
