[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
evm_version = "prague"
optimizer_runs = 800
via_ir = false
ffi = true

[rpc_endpoints]
sepolia = "${RPC_SEPOLIA_URL}" 
op_sepolia = "${RPC_OP_SEPOLIA_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
